---
- name: Dev YML
  hosts: localhost
  gather_facts: false
  vars:
    ubuntu_release: jammy
  tasks:
    - name: Install GPG
      become: true
      apt:
        name: 
          - gnupg
    - name: Get Clang-18 Signature
      become: true
      apt_key:
        url: https://apt.llvm.org/llvm-snapshot.gpg.key

    - name: Add LLVM APT Repo
      become: True
      apt_repository:
        repo: deb http://apt.llvm.org/{{ ubuntu_release }}/ llvm-toolchain-{{ ubuntu_release }}-18 main
        filename: llvm

    - name: Get CMake Signature
      become: True
      apt_key:
        url: https://apt.kitware.com/keys/kitware-archive-latest.asc
        keyring: /usr/share/keyrings/kitware-archive-keyring.gpg

    - name: Add CMake APT Repo
      become: True
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ {{ ubuntu_release }} main
        filename: kitware

    - name: Install Apt Packages
      become: true
      apt:
        name: 
          - libxkbcommon-dev
          - cmake 
          - clang-18
          - libxinerama-dev
          - libxcursor-dev
          - libxi-dev
          - xorg-dev
          - libx11-dev
          - libxrandr-dev
          - mesa-common-dev
          - libx11-xcb-dev
          - pkg-config
          - nodejs
          - npm
        state: latest
        update_cache: true  

    - name: Fetch WebGPU Deps
      command: python3 tools/fetch_dawn_dependencies.py --use-test-deps