add_subdirectory(deps/glfw SYSTEM EXCLUDE_FROM_ALL)
add_subdirectory(deps/webgpu SYSTEM EXCLUDE_FROM_ALL)
add_subdirectory(deps/glfw3webgpu SYSTEM EXCLUDE_FROM_ALL)
add_subdirectory(deps/glm SYSTEM EXCLUDE_FROM_ALL)
add_subdirectory(deps/assimp-3.3.1 SYSTEM EXCLUDE_FROM_ALL)
add_subdirectory(deps/imgui SYSTEM EXCLUDE_FROM_ALL)
add_subdirectory(deps/eigen-3.4.0 SYSTEM EXCLUDE_FROM_ALL)