name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:  # This should be at the job level
      image: ghcr.io/jbrhm/orientation-viz-style-check-ghcr:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}
      volumes:
        - ${{ github.workspace }}/src:/app/src
        - ${{ github.workspace }}/style.sh:/app/style.sh

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Run Style Checker
      run: cd /app && sudo -v && sudo ./style.sh
