name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  login-to-ghcr:
    name: Log In To GHCR
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  check-style:
    name: Run Style Checker
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/jbrhm/orientation-viz-style-check-ghcr:latest
      volumes:
        - my-app:/app
    steps:
      - name: Run Style Checker
        run: ./style.sh
