name: GitHub Actions Demo
run-name: Style-Check
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Orientation Visualizer
      uses: jbrhm
      with:
        owner: 'jbrhm'
        repository: 'OrientationVisualizer'
        access-token: ${{ secrets.ACCESS_TOKEN }}
    - name: Access repository content
      run: |
        cd OrientationVisualizer
        ls -la
