name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:  # This should be at the job level
      image: ghcr.io/jbrhm/orientation-viz-style-check-ghcr:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}
      volumes:
        - my-app:/app

    steps:
    - name: Change Directories
      run: cd /app
    - name: Run Style Checker
      run: ./style.sh
