name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:  # This should be at the job level
      image: ghcr.io/jbrhm/orientation-viz-style-check-ghcr:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}
      volumes:
        path: /mnt/workspace
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Copy subfolder to mounted volume
      run: |
        mkdir -p /mnt/workspace/src
        cp -r ${{ github.workspace }}/src/* /mnt/workspace/src/
    - name: Run Style Checker
      run: cd /mnt/workspace && ./style.sh
