name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-style:
    name: Run Style Checker
    runs-on: ubuntu-latest
    container:
      image: jbrhm/orientation-viz-style-check-ghcr:latest
      volumes:
        - my-app:/app
    steps:
      - name: Run Style Checker
        run: ./style.sh
