name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:  # This should be at the job level
      image: ghcr.io/jbrhm/orientation-viz-style-check-ghcr:latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        
    - name: Run custom commands inside the container
      run: |
        echo "Running commands inside the container"
        # Add your commands to run inside the container here
